// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package handler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionCheckerClient is the client API for SessionChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionCheckerClient interface {
	Create(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*SessionID, error)
	Get(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*SessionInfo, error)
	Delete(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Nothing, error)
}

type sessionCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionCheckerClient(cc grpc.ClientConnInterface) SessionCheckerClient {
	return &sessionCheckerClient{cc}
}

func (c *sessionCheckerClient) Create(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*SessionID, error) {
	out := new(SessionID)
	err := c.cc.Invoke(ctx, "/handler.SessionChecker/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionCheckerClient) Get(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*SessionInfo, error) {
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, "/handler.SessionChecker/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionCheckerClient) Delete(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/handler.SessionChecker/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionCheckerServer is the server API for SessionChecker service.
// All implementations must embed UnimplementedSessionCheckerServer
// for forward compatibility
type SessionCheckerServer interface {
	Create(context.Context, *SessionInfo) (*SessionID, error)
	Get(context.Context, *SessionID) (*SessionInfo, error)
	Delete(context.Context, *SessionID) (*Nothing, error)
	mustEmbedUnimplementedSessionCheckerServer()
}

// UnimplementedSessionCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedSessionCheckerServer struct {
}

func (UnimplementedSessionCheckerServer) Create(context.Context, *SessionInfo) (*SessionID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSessionCheckerServer) Get(context.Context, *SessionID) (*SessionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSessionCheckerServer) Delete(context.Context, *SessionID) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSessionCheckerServer) mustEmbedUnimplementedSessionCheckerServer() {}

// UnsafeSessionCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionCheckerServer will
// result in compilation errors.
type UnsafeSessionCheckerServer interface {
	mustEmbedUnimplementedSessionCheckerServer()
}

func RegisterSessionCheckerServer(s grpc.ServiceRegistrar, srv SessionCheckerServer) {
	s.RegisterService(&SessionChecker_ServiceDesc, srv)
}

func _SessionChecker_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionCheckerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/handler.SessionChecker/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionCheckerServer).Create(ctx, req.(*SessionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionChecker_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionCheckerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/handler.SessionChecker/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionCheckerServer).Get(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionChecker_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionCheckerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/handler.SessionChecker/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionCheckerServer).Delete(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionChecker_ServiceDesc is the grpc.ServiceDesc for SessionChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handler.SessionChecker",
	HandlerType: (*SessionCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SessionChecker_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SessionChecker_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SessionChecker_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}
