version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - $PWD/rabbitmq/data/:$HOME/.log/var/lib/rabbitmq/
            - $PWD/rabbitmq/log/:$HOME/.log/var/log/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3

    redis:
        image: "redis:alpine"
        command: redis-server --port 6380
        environment: 
            - TZ=Europe/Moscow
            - REDIS_REPLICATION_MODE=master
        ports:
            - "6380:6380"
        volumes:
            - $PWD/redis-data:/var/lib/redis
            - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
        healthcheck:
            test: ["CMD", "redis-cli","ping"]
            interval: 30s
            timeout: 10s
            retries: 5

    postgres:
        image: postgres:latest
        container_name: db_postgres
        command: -p 5433 
        environment:
            - POSTGRES_USER=backend_ldbr
            - POSTGRES_PASSWORD=backend_LDBR_password
            - POSTGRES_DB=backend_ldbr_db
            - DATABASE_HOST=db
            - TZ=Europe/Moscow
        ports:
            - "5433:5433"
        volumes:
            - database_postgres:/var/lib/postgresql/data
        healthcheck:
            test: /usr/bin/pg_isready
            interval: 30s
            timeout: 10s
            retries: 5

    email:
        build:
            context: .
            dockerfile: ./Dockerfile-email
        container_name: "2021_2_LadnoDavayteBezRoflov_Email"
        ports:
            - "8083:8083"
        expose:
            - "8083"
        environment:
            - DB_PORT=5433
            - POSTGRES_USER=backend_ldbr
            - POSTGRES_PASSWORD=backend_LDBR_password
            - POSTGRES_DB=backend_ldbr_db
            - DATABASE_HOST=db
        volumes:
            - ./:/email
        restart: on-failure
        depends_on:
            - rabbitmq
            - postgres
        links:
            - "rabbitmq:rabbitmq"
            - "postgres:db"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8082" ]
            interval: 30s
            timeout: 10s
            retries: 5

    session:
        environment:
            - REDIS_PORT=6380
        build:
            context: .
            dockerfile: ./Dockerfile-session
        container_name: "2021_2_LadnoDavayteBezRoflov_Session"
        ports:
            - "8081:8081"
            - "8082:8082"
        expose:
            - "8081"
            - "8082"
        volumes:
            - ./:/session
        restart: on-failure
        depends_on:
            - redis
        links:
            - "redis:redis"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
            interval: 30s
            timeout: 10s
            retries: 5

    backend:
        environment:
            - DB_PORT=5433
            - POSTGRES_USER=backend_ldbr
            - POSTGRES_PASSWORD=backend_LDBR_password
            - POSTGRES_DB=backend_ldbr_db
            - DATABASE_HOST=db
            - FRONTEND_ADDRESS=95.163.213.142
            - GIN_MODE=debug
            - TZ=Europe/Moscow
            - PUBLIC_DIR=/assets
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: "2021_2_LadnoDavayteBezRoflov_Backend"
        ports: 
            - "8000:8000"
        expose:
            - "8000"
        volumes:
            - ./:/backend
            - /home/ubuntu/01-frontend/2021_2_LadnoDavayteBezRoflov/public/assets:/assets
        restart: on-failure
        depends_on:
            - postgres
            - session
        links:
            - "postgres:db"
            - "session:session"
            - "rabbitmq:rabbitmq"

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 9100:9100
        restart: always
        deploy:
            mode: global

    prometheus:
        image: "prom/prometheus"
        ports:
            - "9090:9090"
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        volumes:
            - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

    grafana:
        image: "grafana/grafana"
        ports:
            - "3000:3000"
        volumes:
            - "./grafana:/var/lib/grafana:cached"

volumes:
    .:
    database_postgres:
