# syntax=docker/dockerfile:1
##############################
# Dockerfile to run backend  #
# Based on golang:latest     #
##############################

FROM golang:latest

WORKDIR /email

RUN go install github.com/githubnemo/CompileDaemon@latest

CMD /bin/bash -c '$GOPATH/bin/CompileDaemon -log-prefix=false -polling=true -polling-interval=500 -build="go build ./cmd/email/" -command="./email"'

EXPOSE 8082

HEALTHCHECK CMD netstat -an | grep 8082 > /dev/null; if [ 0 != $? ]; then exit 1; fi;

LABEL \
      name="2021_2_LadnoDavayteBezRoflov_Email" \
      description="Launch LadnoDavayteBezRoflov_Email" \
      version="1.0" \
      maintainer=""
