// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF434a83fDecodeBackendServerAppApiModels(in *jlexer.Lexer, out *CheckListItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chliid":
			out.CHLIID = uint(in.Uint())
		case "chlid":
			out.CHLID = uint(in.Uint())
		case "text":
			out.Text = string(in.String())
		case "status":
			out.Status = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF434a83fEncodeBackendServerAppApiModels(out *jwriter.Writer, in CheckListItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chliid\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.CHLIID))
	}
	{
		const prefix string = ",\"chlid\":"
		out.RawString(prefix)
		out.Uint(uint(in.CHLID))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Bool(bool(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckListItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF434a83fEncodeBackendServerAppApiModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckListItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF434a83fEncodeBackendServerAppApiModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckListItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF434a83fDecodeBackendServerAppApiModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckListItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF434a83fDecodeBackendServerAppApiModels(l, v)
}
