// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6d88e0beDecodeBackendServerAppApiModels(in *jlexer.Lexer, out *CheckList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chlid":
			out.CHLID = uint(in.Uint())
		case "cid":
			out.CID = uint(in.Uint())
		case "title":
			out.Title = string(in.String())
		case "check_list_items":
			if in.IsNull() {
				in.Skip()
				out.CheckListItems = nil
			} else {
				in.Delim('[')
				if out.CheckListItems == nil {
					if !in.IsDelim(']') {
						out.CheckListItems = make([]CheckListItem, 0, 1)
					} else {
						out.CheckListItems = []CheckListItem{}
					}
				} else {
					out.CheckListItems = (out.CheckListItems)[:0]
				}
				for !in.IsDelim(']') {
					var v1 CheckListItem
					(v1).UnmarshalEasyJSON(in)
					out.CheckListItems = append(out.CheckListItems, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6d88e0beEncodeBackendServerAppApiModels(out *jwriter.Writer, in CheckList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chlid\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.CHLID))
	}
	{
		const prefix string = ",\"cid\":"
		out.RawString(prefix)
		out.Uint(uint(in.CID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"check_list_items\":"
		out.RawString(prefix)
		if in.CheckListItems == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.CheckListItems {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6d88e0beEncodeBackendServerAppApiModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6d88e0beEncodeBackendServerAppApiModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6d88e0beDecodeBackendServerAppApiModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6d88e0beDecodeBackendServerAppApiModels(l, v)
}
