// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3a50a0cfDecodeBackendServerAppApiModels(in *jlexer.Lexer, out *Color) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "clrid":
			out.CLRID = uint(in.Uint())
		case "color_name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3a50a0cfEncodeBackendServerAppApiModels(out *jwriter.Writer, in Color) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"clrid\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.CLRID))
	}
	{
		const prefix string = ",\"color_name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Color) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3a50a0cfEncodeBackendServerAppApiModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Color) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3a50a0cfEncodeBackendServerAppApiModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Color) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3a50a0cfDecodeBackendServerAppApiModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Color) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3a50a0cfDecodeBackendServerAppApiModels(l, v)
}
