// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson13673cd6DecodeBackendServerAppApiModels(in *jlexer.Lexer, out *Tag) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tgid":
			out.TGID = uint(in.Uint())
		case "bid":
			out.BID = uint(in.Uint())
		case "tag_name":
			out.Title = string(in.String())
		case "color":
			easyjson13673cd6DecodeBackendServerAppApiModels1(in, &out.Color)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson13673cd6EncodeBackendServerAppApiModels(out *jwriter.Writer, in Tag) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tgid\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.TGID))
	}
	{
		const prefix string = ",\"bid\":"
		out.RawString(prefix)
		out.Uint(uint(in.BID))
	}
	{
		const prefix string = ",\"tag_name\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"color\":"
		out.RawString(prefix)
		easyjson13673cd6EncodeBackendServerAppApiModels1(out, in.Color)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Tag) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson13673cd6EncodeBackendServerAppApiModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Tag) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson13673cd6EncodeBackendServerAppApiModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Tag) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson13673cd6DecodeBackendServerAppApiModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Tag) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson13673cd6DecodeBackendServerAppApiModels(l, v)
}
func easyjson13673cd6DecodeBackendServerAppApiModels1(in *jlexer.Lexer, out *Color) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "clrid":
			out.CLRID = uint(in.Uint())
		case "color_name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson13673cd6EncodeBackendServerAppApiModels1(out *jwriter.Writer, in Color) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"clrid\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.CLRID))
	}
	{
		const prefix string = ",\"color_name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}
