// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7c9ac09dDecodeBackendServerAppApiModels(in *jlexer.Lexer, out *UsersSearchInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(UsersSearchInfo, 0, 1)
			} else {
				*out = UsersSearchInfo{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 UserSearchInfo
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c9ac09dEncodeBackendServerAppApiModels(out *jwriter.Writer, in UsersSearchInfo) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v UsersSearchInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c9ac09dEncodeBackendServerAppApiModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UsersSearchInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c9ac09dEncodeBackendServerAppApiModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UsersSearchInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c9ac09dDecodeBackendServerAppApiModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UsersSearchInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c9ac09dDecodeBackendServerAppApiModels(l, v)
}
func easyjson7c9ac09dDecodeBackendServerAppApiModels1(in *jlexer.Lexer, out *UserSearchInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "uid":
			out.UID = uint(in.Uint())
		case "userName":
			out.Login = string(in.String())
		case "avatar":
			out.Avatar = string(in.String())
		case "added":
			out.Added = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c9ac09dEncodeBackendServerAppApiModels1(out *jwriter.Writer, in UserSearchInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uid\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.UID))
	}
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix)
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"avatar\":"
		out.RawString(prefix)
		out.String(string(in.Avatar))
	}
	{
		const prefix string = ",\"added\":"
		out.RawString(prefix)
		out.Bool(bool(in.Added))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserSearchInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c9ac09dEncodeBackendServerAppApiModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserSearchInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c9ac09dEncodeBackendServerAppApiModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserSearchInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c9ac09dDecodeBackendServerAppApiModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserSearchInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c9ac09dDecodeBackendServerAppApiModels1(l, v)
}
