global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'docker.for.linux.localhost:8000' ]

  - job_name: 'session microservice'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'docker.for.linux.localhost:8082' ]

  - job_name: 'email microservice'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'docker.for.linux.localhost:8083' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'docker.for.linux.localhost:9100' ]
