name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
    
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          skip-go-installation: true

      - name: Run tests
        run: sudo apt-get install libwebp-dev; go clean -testcache; go test -cover ./... -race
